module.exports = [    
    { base: "Achluo", explanation: "darkness" },
    { base: "Acoustico", explanation: "noise" },
    { base: "Acro", explanation: "heights" },
    { base: "Aero", explanation: "aircraft or flying" },
    { base: "Agora", explanation: "open places" },
    { base: "Agyro", explanation: "crossing streets" },
    { base: "Aichmo", explanation: "sharp or pointed objects such as a needle or knife" },
    { base: "Ailuro", explanation: "cats" },
    { base: "Alektoro", explanation: "chickens" },
    { base: "Anatidae", explanation: "ducks" },
    { base: "Algo", explanation: "pain" },
    { base: "Ancrao", explanation: "wind or drafts" },
    { base: "Andro", explanation: "adult men" },
    { base: "Apeiro", explanation: "excessive infinity and the uncountable" },
    { base: "Aphenphosm", explanation: "being touched" },
    { base: "Apotemno", explanation: "becoming an amputee" },
    { base: "Aqua", explanation: "water" },
    { base: "Arachno", explanation: "spiders and other arachnids such as scorpions" },
    { base: "Astra", explanation: "thunder and lightning" },
    { base: "Atelo", explanation: "imperfection" },
    { base: "Auto", explanation: "isolation" },
    { base: "Bacterio", explanation: "bacteria" },
    { base: "Baso", explanation: "associated with astasia-abasia (walking/standing erect) and a falling" },
    { base: "basi", explanation: "associated with astasia-abasia (walking/standing erect) and a falling" },
    { base: "Batracho", explanation: "frogs and other amphibians" },
    { base: "Belone", explanation: "needles" },
    { base: "Biblio", explanation: "books" },
    { base: "Caco", explanation: "ugliness" },
    { base: "aschimo", explanation: "ugliness" },
    { base: "Carcino", explanation: "cancer" },
    { base: "Catoptro", explanation: "mirrors" },
    { base: "Chemo", explanation: "chemicals" },
    { base: "Chero", explanation: "happiness" },
    { base: "Chiropto", explanation: "bats," },
    { base: "Chromo", explanation: "colors" },
    { base: "chromato", explanation: "colors" },
    { base: "Chrono", explanation: "time and time moving forward" },
    { base: "Chronomentro", explanation: "clocks" },
    { base: "Cibo", explanation: "aversion to food, synonymous with anorexia nervosa" },
    { base: "sito", explanation: "aversion to food, synonymous with anorexia nervosa" },
    { base: "Claustro", explanation: "having no escape and being closed in" },
    { base: "Coimetro", explanation: "cemeteries" },
    { base: "Copro", explanation: "feces or defecation" },
    { base: "Coulro", explanation: "clowns" },
    { base: "Cyber", explanation: "computers" },
    { base: "Cyno", explanation: "dogs" },
    { base: "odonto", explanation: "dentists and dental procedures" },
    { base: "Dento", explanation: "dentists" },
    { base: "Domato", explanation: "houses" },
    { base: "Driving", explanation: "driving" },
    { base: "Dysmorpho, body dysmorphic disorder", explanation: "a phobic obsession with a real or imaginary body defect" },
    { base: "Eco", explanation: "cataclysmic environmental change" },
    { base: "Eisoptro", explanation: "mirrors or seeing one's reflection in a mirror" },
    { base: "Emeto", explanation: "vomiting" },
    { base: "Enochlo", explanation: "crowds" },
    { base: "Entomo", explanation: "insects" },
    { base: "Ephebi", explanation: "youth; inaccurate, exaggerated and sensational characterization of young people" },
    { base: "Equino", explanation: "horses" },
    { base: "Ergo", explanation: "work or functioning, or a surgeon's operating" },
    { base: "ergasio", explanation: "work or functioning, or a surgeon's operating" },
    { base: "Eroto", explanation: "sexual love or sexual abuse" },
    { base: "Erythro", explanation: "the color red or of blushing" },
    { base: "eryto", explanation: "the color red, or of blushing" },
    { base: "ereutho", explanation: "the color red or of blushing" },
    { base: "Euroto", explanation: "aversion to female genitals" },
    { base: "Frigo", explanation: "becoming too cold" },
    { base: "Gamo", explanation: "marriage" },
    { base: "Geloto", explanation: "being laughed at" },
    { base: "Gephyro", explanation: "bridges" },
    { base: "Geno", explanation: "sexual intercourse" },
    { base: "coito", explanation: "sexual intercourse" },
    { base: "Genu", explanation: "knees or the act of kneeling" },
    { base: "Gerasco", explanation: "growing old or aging" },
    { base: "Geronto", explanation: "growing old or of the elderly" },
    { base: "Globo", explanation: "balloons" },
    { base: "Glosso", explanation: "speaking in public or of trying to speak" },
    { base: "Gymno", explanation: "nudity" },
    { base: "Gyno", explanation: "adult women" },
    { base: "Halito", explanation: "bad breath" },
    { base: "Haphe", explanation: "being touched" },
    { base: "Heptadeka", explanation: "the number 17" },
    { base: "heptadeca", explanation: "the number 17" },
    { base: "Hedono", explanation: "obtaining pleasure" },
    { base: "Helio", explanation: "the sun or sunlight" },
    { base: "Helmintho", explanation: "worms" },
    { base: "scoleci", explanation: "worms" },
    { base: "vermi", explanation: "worms" },
    { base: "Hemo", explanation: "blood" },
    { base: "haemo", explanation: "blood" },
    { base: "Herpeto", explanation: "reptiles or amphibians" },
    { base: "Hexakosioihexekontahexa", explanation: "the number 666" },
    { base: "Hippo", explanation: "horses" },
    { base: "Hodo", explanation: "travel" },
    { base: "Hydro", explanation: "wate" },
    { base: "Hypno", explanation: "sleep or nightmares" },
    { base: "somni", explanation: "sleep or nightmares" },
    { base: "Hypochondria", explanation: "illness" },
    { base: "Ichthyo", explanation: "fish of eating fish or of dead fish" },
    { base: "Insecto", explanation: "insects" },
    { base: "Koumpouno", explanation: "buttons on clothing" },
    { base: "Lilapso", explanation: "tornadoes or hurricanes" },
    { base: "Lepidoptero", explanation: "butterflies and moths" },
    { base: "Mageiroco", explanation: "cooking" },
    { base: "Masklo", explanation: "people in masks, costumes and mascots" },
    { base: "Melano", explanation: "the color black" },
    { base: "Melisso", explanation: "bees" },
    { base: "api", explanation: "bees" },
    { base: "Mono", explanation: "being alone or isolated or of one's self" },
    { base: "Muso", explanation: "mice or rats" },
    { base: "muro", explanation: "mice or rats" },
    { base: "suri", explanation: "mice or rats" },
    { base: "Myrmeco", explanation: "ants" },
    { base: "Myso", explanation: "germs, contamination or dirt" },
    { base: "germo", explanation: "germs, contamination or dirt" },
    { base: "Necro", explanation: "death or the dead" },
    { base: "Neo", explanation: "newness, novelty, change or progress" },
    { base: "caino", explanation: "newness, novelty, change or progress" },
    { base: "cainoto", explanation: "newness, novelty, change or progress" },
    { base: "cento", explanation: "newness, novelty, change or progress" },
    { base: "kainolo", explanation: "newness, novelty, change or progress" },
    { base: "kaino", explanation: "newness, novelty, change or progress" },
    { base: "metathesio", explanation: "newness, novelty, change or progress" },
    { base: "proso", explanation: "newness, novelty, change or progress" },
    { base: "Nocti", explanation: "the night" },
    { base: "Nomo", explanation: "being out of mobile phone contact" },
    { base: "Nosocome", explanation: "hospitals" },
    { base: "Noso", explanation: "contracting a disease" },
    { base: "Nosto", explanation: "returning home" },
    { base: "eco", explanation: "returning home" },
    { base: "Numero", explanation: "numbers" },
    { base: "Nycto", explanation: "darkness" },
    { base: "Achluo ", explanation: "darkness" },
    { base: "Lygo ", explanation: "darkness " },
    { base: "Scoto", explanation: "darkness" },
    { base: "Obeso", explanation: "gaining weight" },
    { base: "Oiko", explanation: "home surroundings and household appliances" },
    { base: "Ommeta", explanation: "eyes" },
    { base: "Oneiro", explanation: "dreams" },
    { base: "Ophidio", explanation: "snakes" },
    { base: "Ophthalmo", explanation: "being stared at" },
    { base: "Ornitho", explanation: "birds" },
    { base: "Osmo", explanation: "odors" },
    { base: "olfacto", explanation: "odors" },
    { base: "Ostracono", explanation: "shellfish" },
    { base: "Pan", explanation: "everything or constant an unknown cause" },
    { base: "Pedo", explanation: "babies and children" },
    { base: "paedo", explanation: "babies and children" },
    { base: "pedia", explanation: "babies and children" },
    { base: "Phago", explanation: "swallowing" },
    { base: "Phallo", explanation: "erections" },
    { base: "Pharmaco", explanation: "medications" },
    { base: "Phasmo", explanation: "ghosts or phantoms" },
    { base: "Philo", explanation: "love" },
    { base: "Phobo", explanation: "having a " },
    { base: "Phono", explanation: "loud sounds or voices" },
    { base: "Pogono", explanation: "beards" },
    { base: "Porno", explanation: "dislike or pornography;" },
    { base: "Porphyro", explanation: "the color purple" },
    { base: "Pteromerhano", explanation: "flying" },
    { base: "Pyro", explanation: "fire" },
    { base: "Radio", explanation: "radioactivity or X-rays" },
    { base: "Ranida", explanation: "frogs" },
    { base: "Scopo", explanation: "being looked at or stared at" },
    { base: "Sexo", explanation: "sexual organs or sexual activities" },
    { base: "Siderodromo", explanation: "trains or railroads" },
    { base: "Social ", explanation: "people or social situations" },
    { base: "Somni", explanation: "sleep" },
    { base: "Spectro", explanation: "mirrors" },
    { base: "Stasi", explanation: "standing or walking" },
    { base: "Submechano", explanation: "partially or fully submerged man-made objects" },
    { base: "Tapho", explanation: "graves or of being placed in a grave while still alive" },
    { base: "taphe", explanation: "graves or of being placed in a grave while still alive" },
    { base: "Techno", explanation: "advanced technology (see also Luddite)" },
    { base: "Telephone ", explanation: "making or taking telephone calls" },
    { base: "Terato", explanation: "giving birth to a monster or a disfigured foetus" },
    { base: "Tetra", explanation: "the number 4" },
    { base: "Thalasso", explanation: "the sea or of being in the ocean" },
    { base: "Thanato", explanation: "dying" },
    { base: "Thermo", explanation: "intolerance to high temperatures" },
    { base: "Toko", explanation: "childbirth or pregnancy" },
    { base: "Tomo", explanation: "invasive medical procedure" },
    { base: "Tonitro", explanation: "thunder" },
    { base: "Toxi", explanation: "being poisoned" },
    { base: "Traumato", explanation: "having an injury" },
    { base: "Tricho", explanation: "delusional something in the roots of the hair that stops it from growing, or hair loss" },
    { base: "Triskaideka", explanation: "the number 13" },
    { base: "terdeka", explanation: "the number 13" },
    { base: "Trypano", explanation: "needles or injections" },
    { base: "belone", explanation: "needles or injections" },
    { base: "eneto", explanation: "needles or injections" },
    { base: "Trypo", explanation: "holes or textures with a pattern of holes" },
    { base: "Veho", explanation: "driving" },
    { base: "Vermino", explanation: "germs" },
    { base: "Workplace ", explanation: "the workplace" },
    { base: "Xantho", explanation: "the color yellow" },
    { base: "Zoo", explanation: "animals" },
    { base: "Ace", explanation: "asexual people" },
    { base: "Bi", explanation: "bisexuality or bisexuals" },
    { base: "Ephebi", explanation: "youth" },
    { base: "Geronto", explanation: "aging or the elderly" },
    { base: "gerasco", explanation: "aging or the elderly" },
    { base: "Hetero", explanation: "heterosexuals" },
    { base: "Homo", explanation: "homosexuality, homosexuals, or gays (as opposed to lesbians)" },
    { base: "Lesbo", explanation: "lesbians" },
    { base: "Pedo", explanation: "babies or children" },
    { base: "Psycho", explanation: "mental illness or the mentally ill" },
    { base: "Trans", explanation: "transgender people" },
    { base: "Afro", explanation: "Africans" },
    { base: "Albano", explanation: "Albanians" },
    { base: "Anglo", explanation: "England or English culture" },
    { base: "Christiano", explanation: "Christians" },
    { base: "Germano", explanation: "Germans" },
    { base: "Hindu", explanation: "Hindus" },
    { base: "Hispano", explanation: "Hispanic people, Hispanic culture and the Spanish language" },
    { base: "Hungaro", explanation: "Hungarians" },
    { base: "Indo", explanation: "India or Indian culture" },
    { base: "Irano", explanation: "Iran or Iranian culture" },
    { base: "Islamo", explanation: "Muslims" },
    { base: "Judeo", explanation: "Jews" },
    { base: "Luso", explanation: "the Portuguese, Portuguese culture and the Portuguese language" },
    { base: "Nippono", explanation: "the Japanese" },
    { base: "Koryo", explanation: "the Koreans" },
    { base: "Latino", explanation: "Latin people" },
    { base: "Negro", explanation: "black people" },
    { base: "Polono", explanation: "the Polish" },
    { base: "Russo", explanation: "Russians" },
    { base: "Shia", explanation: "Shiites" },
    { base: "Sino", explanation: "Chinese people" },
    { base: "Sunni", explanation: "Sunnis" },
    { base: "Turco", explanation: "Turks" },
    { base: "Xeno", explanation: "foreigners" }
]
